CREATE DATABASE SCORE;
USE SCORE;

CREATE TABLE SCHOOL (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	PROV_CODE INTEGER UNSIGNED NOT NULL,
	SCHOOL VARCHAR(255) NOT NULL,
	SCH_CODE INTEGER UNSIGNED NOT NULL,
	PROP VARCHAR(10),
	DETAIL TEXT,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE PROSPECTUS (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SCH_CODE INTEGER UNSIGNED NOT NULL,
	YEAR INTEGER UNSIGNED NOT NULL,
	CONTENT TEXT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE SCH_SCORE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SCH_CODE INTEGER UNSIGNED NOT NULL,
	STU_PROV_CODE INTEGER UNSIGNED NOT NULL,
	CATEGORY VARCHAR(10) NOT NULL,
	BATCH VARCHAR(10) NOT NULL,
	YEAR INTEGER UNSIGNED NOT NULL,
	AVG_SCORE INTEGER UNSIGNED,
	HIGHEST_SCORE INTEGER UNSIGNED,
	LOWEST_SCORE INTEGER UNSIGNED,
	PRIMARY KEY (ID),
	UNIQUE (SCH_CODE,STU_PROV_CODE,CATEGORY,BATCH,YEAR)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE SPE_SCORE (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SCH_CODE INTEGER UNSIGNED NOT NULL,
	SPECIALITY VARCHAR(255) NOT NULL,
	STU_PROV_CODE INTEGER UNSIGNED NOT NULL,
	CATEGORY VARCHAR(10) NOT NULL,
	BATCH VARCHAR(10) NOT NULL,
	YEAR INTEGER UNSIGNED NOT NULL,
	AVG_SCORE INTEGER UNSIGNED,
	HIGHEST_SCORE INTEGER UNSIGNED,
	LOWEST_SCORE INTEGER UNSIGNED,
	PRIMARY KEY (ID),
	UNIQUE (SCH_CODE,SPECIALITY,STU_PROV_CODE,CATEGORY,BATCH,YEAR)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE LOG (
	ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	SCH_CODE INTEGER UNSIGNED NOT NULL,
	YEAR INTEGER UNSIGNED NOT NULL,
	STATE INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO LOG VALUES(1,30,2015,0); /* for SCH_SCORE */
INSERT INTO LOG VALUES(2,30,2015,0); /* for SPE_SCORE */